# Generated by Django 5.0.7 on 2024-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
