# Generated by Django 5.0.7 on 2024-08-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('durationHr', models.IntegerField()),
                ('durationMin', models.IntegerField()),
                ('durationSec', models.IntegerField()),
                ('paceMin', models.IntegerField()),
                ('paceSec', models.IntegerField()),
                ('heartrate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('fName', models.CharField(max_length=50)),
                ('lName', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
